import { zodResolver } from "@hookform/resolvers/zod";
import { Preference, Season } from "@prisma/client";
import { AnimatePresence, motion } from "framer-motion";
import Head from "next/head";
import { useEffect, useRef, useState } from "react";
import { useForm, type SubmitHandler } from "react-hook-form";
import { z } from "zod";
import type { NextPageWithLayout } from "./_app";

// external imports
import AnimatedText from "@/components/AnimatedText";
import CountUp from "@/components/CountUp";
import SelectBox from "@/components/DropdownSelect";
import SearchableSelect from "@/components/SearchableSelect";
import rawCountries from "@/data/countries.json";
import Layout from "@/layouts/Layout";
import { api } from "@/utils/api";
import Button from "@/components/Button";

const schema = z.object({
  country: z.string({ required_error: "Please select a country" }),
  preference: z.nativeEnum(Preference),
  season: z.nativeEnum(Season),
});

type Inputs = z.infer<typeof schema>;

const Home: NextPageWithLayout = () => {
  const countries = rawCountries.map((country) => country.name);
  const [places, setPlaces] = useState<string[]>();
  const generatedRef = useRef<HTMLDivElement>(null);

  // genereate places mutation
  const placesMutaion = api.openai.generatePlaces.useMutation({
    onSuccess: (data) => {
      console.log(data);
    },
    onError: (error) => {
      console.log(error);
    },
  });

  // react-hook-form
  const { handleSubmit, control, formState } = useForm<Inputs>({
    resolver: zodResolver(schema),
  });
  const onSubmit: SubmitHandler<Inputs> = (data) => {
    console.log(data);
  };

  // framer motion
  const container = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
        delayChildren: 0.5,
      },
    },
  };
  const item = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 },
  };

  // scroll to generated cities
  useEffect(() => {
    if (!generatedRef.current) return;
    generatedRef.current.scrollIntoView({ behavior: "smooth" });
  }, [places]);

  return (
    <>
      <Head>
        <title>Next Tour</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto mt-28 mb-14 grid w-full max-w-4xl gap-10 px-4">
        <div className="grid place-items-center gap-2 sm:gap-4">
          <h1 className="text-center text-3xl font-semibold text-white sm:text-6xl">
            Generate your next <span className="text-indigo-500">tour</span>{" "}
            destination with AI
          </h1>
          <span className="text-center text-lg text-gray-400 sm:text-xl">
            Total <CountUp className="text-indigo-500" end={69} /> destinations
            generated so far
          </span>
          <AnimatedText
            className="mx-auto from-indigo-500 to-indigo-500 text-2xl font-semibold sm:text-3xl"
            words={countries}
            defaultWord="Bangladesh"
          />
        </div>
        <form
          aria-label="generate city from"
          className="mx-auto grid w-full max-w-2xl gap-5"
          onSubmit={(...args) => void handleSubmit(onSubmit)(...args)}
        >
          <fieldset className="grid gap-3">
            <label htmlFor="country" className="text-base text-white">
              <span className="rounded-full text-gray-400">1.</span> Select your
              country
            </label>
            <SearchableSelect
              name="country"
              control={control}
              options={countries}
            />
            {formState.errors.country ? (
              <span className="text-base text-red-500">
                {formState.errors.country.message}
              </span>
            ) : null}
          </fieldset>
          <fieldset className="grid gap-3">
            <label htmlFor="preference" className="text-base text-white">
              <span className="rounded-full text-gray-400">2.</span> Select your
              tour preference
            </label>
            <SelectBox
              name="preference"
              control={control}
              options={Object.values(Preference)}
            />

            {formState.errors.preference ? (
              <span className="text-base text-red-500">
                {formState.errors.preference.message}
              </span>
            ) : null}
          </fieldset>
          <fieldset className="grid gap-3">
            <label htmlFor="season" className="text-base text-white">
              <span className="rounded-full text-gray-400">3.</span> Select your
              tour season
            </label>
            <SelectBox
              name="season"
              control={control}
              options={Object.values(Season)}
            />

            {formState.errors.season ? (
              <span className="text-base text-red-500">
                {formState.errors.season.message}
              </span>
            ) : null}
          </fieldset>
          <Button
            aria-label="generate your places"
            variant="primary"
            loading={placesMutaion.isLoading}
            disabled={placesMutaion.isLoading}
          >
            {placesMutaion.isLoading ? "Loading..." : "Generate your places"}
          </Button>
        </form>
        {places ? (
          <AnimatePresence mode="wait">
            <motion.div
              ref={generatedRef}
              className="mx-auto grid w-full max-w-2xl gap-8"
            >
              <h2 className="text-center text-3xl font-bold text-white sm:text-4xl">
                Your generated destinations
              </h2>
              <motion.div
                className="grid w-full place-items-center gap-3"
                variants={container}
                initial="hidden"
                animate="visible"
              >
                {places.map((place) => (
                  <motion.div
                    key={place}
                    className="w-full max-w-2xl rounded-md bg-neutral-800 p-4 shadow-md ring-1 ring-gray-500"
                    variants={item}
                  >
                    <h3 className="text-base font-semibold text-white">
                      {place}
                    </h3>
                  </motion.div>
                ))}
              </motion.div>
            </motion.div>
          </AnimatePresence>
        ) : null}
      </main>
    </>
  );
};

export default Home;

Home.getLayout = (page) => <Layout>{page}</Layout>;
